name: Release

on:
  push:
    branches:
      - main  

jobs:
  release:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'  

      - name: Install dependencies
        run: yarn install  

      - name: Set up Semantic Release
        run: yarn add semantic-release @semantic-release/github @semantic-release/npm -D

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
