name: Upload to Localazy

on: 
  push:
    paths:
      - 'locales/en.json'

jobs:
  localazy-upload:
    name: Upload strings to Localazy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Upload translations
        uses: localazy/upload@v1
        with:
          project_id: ${{ secrets.LOCALAZY_PROJECT_ID }}
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
