name: Upload to Localazy

on: 
  push:
    paths:
      - 'locales/en.json'  

jobs:
  localazy-upload:
    name: Upload strings to Localazy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  

      - name: Install Localazy CLI
        run: npm install -g @localazy/cli 

      - name: Upload translations
        run: localazy upload  
        env:
          LOCALAZY_PROJECT_ID: ${{ secrets.LOCALAZY_PROJECT_ID }}
          LOCALAZY_READ_KEY: ${{ secrets.LOCALAZY_READ_KEY }}
          LOCALAZY_WRITE_KEY: ${{ secrets.LOCALAZY_WRITE_KEY }}
